import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>localStorage.setItem('dook-save',JSON.stringify({name:'Clark',unlocked:3,music:false,sound:false})));
await page.goto('http://localhost:5173');await page.locator('[data-action="chapters"]').click();await page.screenshot({path:'output/qa/chapters-final.png'});await page.locator('[data-chapter="2"]').click();await page.locator('[data-action="skip-story"]').click();await page.locator('[data-action="run"]').click();
await page.evaluate(()=>{window.__sceneBot=setInterval(()=>{const s=window.__dook.snapshot();if(s.mode!=='playing')return;const e=window.__dook.getCourse().find(e=>!['coin','heart','finish'].includes(e.type)&&e.distance>s.distance-1.8);if(!e||e.distance-s.distance>19)return;const lane=e.lane===0?1:0;const key=k=>document.body.dispatchEvent(new KeyboardEvent('keydown',{key:k,bubbles:true}));if(s.lane<lane)key('ArrowRight');if(s.lane>lane)key('ArrowLeft');},30);});
await page.waitForFunction(()=>['result','failed'].includes(window.__dook.snapshot().mode),null,{timeout:65000});expect(await page.evaluate(()=>window.__dook.snapshot().mode)).toBe('result');await page.locator('[data-action="continue"]').click();await page.screenshot({path:'output/qa/ending-final.png'});await page.locator('[data-action="next-story"]').click();await expect(page.locator('.dialogue-content p')).toContainText('Ferret Clark');await page.locator('[data-action="skip-story"]').click();await page.screenshot({path:'output/qa/credits-final.png'});
const outOfBounds=await page.locator('.ending-screen h2').evaluate(e=>e.scrollWidth>e.clientWidth);expect(outOfBounds).toBe(false);await page.locator('[data-action="home"]').click();
await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(200);await page.screenshot({path:'output/qa/title-desktop-final.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await page.screenshot({path:'output/qa/title-mobile-final.png'});
console.log('Final scenes: personalized greeting, credits layout, chapter art and title screens passed.',{errors});expect(errors).toEqual([]);await browser.close();
