import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.locator('[data-action="start"]').click();await page.locator('#player-name').fill('  ');await page.locator('button[type="submit"]').click();await page.locator('#player-name').fill('Quinn');await page.locator('button[type="submit"]').click();await expect(page.locator('.speaker')).toContainText('GOOSE MICHAEL');await page.locator('[data-action="skip-story"]').click();await page.locator('[data-action="run"]').click();
await page.mouse.move(150,400);await page.mouse.down();await page.mouse.move(235,400);await page.mouse.up();expect(await page.evaluate(()=>window.__dook.snapshot().lane)).toBe(1);
await page.mouse.move(150,400);await page.mouse.down();await page.mouse.move(150,315);await page.mouse.up();await page.waitForTimeout(100);expect(await page.evaluate(()=>window.__dook.snapshot().height)).toBeGreaterThan(0);
await page.locator('[data-action="pause"]').click();const before=await page.evaluate(()=>window.__dook.snapshot());await page.locator('#help-button').click();await expect(page.locator('#help-overlay')).toBeVisible();await page.locator('[data-action="close-help"]').click();expect(await page.evaluate(()=>window.__dook.snapshot().distance)).toBe(before.distance);await page.locator('[data-action="home"]').click();
await page.reload();await expect(page.locator('.save-line')).toContainText('FERRET QUINN');await page.locator('[data-action="chapters"]').click();await expect(page.locator('[data-chapter="1"]')).toBeDisabled();await page.locator('[data-chapter="0"]').click();await page.locator('[data-action="skip-story"]').click();await page.locator('[data-action="run"]').click();
// No-input run must fail and allow a clean retry.
await page.waitForFunction(()=>window.__dook.snapshot().mode==='failed',null,{timeout:65000});await page.screenshot({path:'output/qa/retry-mobile.png'});await page.locator('[data-action="retry"]').click();expect(await page.evaluate(()=>window.__dook.snapshot().lives)).toBe(3);await page.locator('[data-action="pause"]').click();await page.locator('[data-action="home"]').click();
for(const viewport of [{width:375,height:667},{width:390,height:844},{width:768,height:1024},{width:1440,height:1000}]){await page.setViewportSize(viewport);await page.waitForTimeout(150);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);expect(overflow).toBe(false);await page.screenshot({path:`output/qa/responsive-${viewport.width}.png`});}
console.log('Touch, whitespace validation, pause/help, persistence, chapter locks, failure/retry and responsive checks passed.');console.log({errors});expect(errors).toEqual([]);await browser.close();
