import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ferret,goose} from './characters.js';
const container=document.querySelector('#viewport');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0xf7edce);const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(6.7,3.1,4.8);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.05,-.3);controls.update();
scene.add(new THREE.HemisphereLight(0xfff7e4,0x9b8056,1.5));const key=new THREE.DirectionalLight(0xffefd0,2.0);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=6;key.shadow.camera.bottom=-6;key.shadow.bias=-.001;scene.add(key);const rim=new THREE.DirectionalLight(0xffffff,.7);rim.position.set(4,3,-4);scene.add(rim);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.ShadowMaterial({opacity:.17}));ground.rotation.x=-Math.PI/2;ground.position.y=-.02;ground.receiveShadow=true;scene.add(ground);
const f=ferret(scene),g=goose(scene);g.group.visible=false;g.treats.visible=true;
const helper=new THREE.SkeletonHelper(f.group);helper.material.depthTest=false;helper.material.transparent=true;helper.material.opacity=.9;helper.visible=false;scene.add(helper);
const gooseHelper=new THREE.SkeletonHelper(g.group);gooseHelper.material.depthTest=false;gooseHelper.visible=false;scene.add(gooseHelper);
let mode='idle',time=0,speed=1,paused=false,showGoose=false,lookOverride=1.13,comparing=false,faceView=false,expression='grin';
function draw(t){
 const airborne=mode==='jump'||mode==='barrel';const q=(t*.65)%1;const jumpHeight=airborne?Math.sin(q*Math.PI)*(mode==='barrel'?1.25:.7):0;
 f.group.position.y=jumpHeight;f.animate(t,mode!=='idle',mode==='slide',{sampleTime:true,expression,motion:mode,height:jumpHeight,roll:mode==='barrel'?q:0,look:lookOverride??(mode==='idle'?.05:0)});g.animate(t);helper.updateMatrixWorld(true);renderer.render(scene,camera);
 document.querySelector('#stats').innerHTML=showGoose?`GOOSE MICHAEL · ${g.rig.bones.length} BONES<br>CONTINUOUS SCULPTED BODY & NECK`:`FERRET · ${f.rig.bones.length} BONES · ${f.rig.mesh.geometry.index.count/3} SKIN TRIANGLES · ${f.stats.expression.toUpperCase()}<br>${f.stats.motion.toUpperCase()} · SPINE FLEX ${f.stats.arch.toFixed(2)} · ROLL ${(f.stats.roll*180/Math.PI).toFixed(0)}°`;
}
function referenceView(){document.body.classList.remove('face-comparing');faceView=false;lookOverride=1.13;controls.target.set(0,1.13,-.15);const distance=Math.max(8.5,7.5/camera.aspect);camera.position.set(6.7,2.95,4.95).normalize().multiplyScalar(distance).add(controls.target);controls.update();}
const resize=()=>{renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();if(comparing&&!faceView)referenceView();};new ResizeObserver(resize).observe(container);resize();
function select(m){mode=m;time=0;lookOverride=m==='idle'?1.13:0;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>select(b.dataset.mode));document.querySelector('#pause').onclick=()=>{paused=!paused;document.querySelector('#pause').textContent=paused?'Play':'Pause';};document.querySelector('#skeleton').onchange=e=>{helper.visible=e.target.checked&&!showGoose;gooseHelper.visible=e.target.checked&&showGoose;};
document.querySelector('#wireframe').onchange=e=>{f.rig.mesh.material.wireframe=e.target.checked;g.rig.mesh.material.wireframe=e.target.checked;};
document.querySelector('#speed').oninput=e=>speed=Number(e.target.value);document.querySelector('#side').onclick=()=>{faceView=false;lookOverride=0;camera.position.set(7,2.0,0);controls.target.set(0,1.0,-.35);controls.update();};document.querySelector('#front').onclick=referenceView;
document.querySelector('#friend').onclick=()=>{showGoose=!showGoose;g.group.visible=showGoose;f.group.visible=!showGoose;helper.visible=document.querySelector('#skeleton').checked&&!showGoose;gooseHelper.visible=document.querySelector('#skeleton').checked&&showGoose;document.querySelector('#caption').textContent=showGoose?'Goose Michael, gelato enthusiast':'The local chaos noodle';};
document.querySelector('#compare').onclick=()=>{comparing=!comparing;document.body.classList.toggle('comparing',comparing);document.querySelector('#compare').classList.toggle('active',comparing);showGoose=false;g.group.visible=false;f.group.visible=true;select('idle');paused=true;document.querySelector('#pause').textContent='Play';document.querySelector('#caption').textContent='Frozen 3D model';referenceView();resize();};
document.querySelector('#face').onclick=()=>{document.body.classList.add('face-comparing');faceView=true;lookOverride=0;select('idle');lookOverride=.18;paused=true;document.querySelector('#pause').textContent='Play';controls.target.set(0,1.84,1.12);camera.position.set(0,1.95,5.2);controls.update();document.querySelector('#caption').textContent='Face · frozen front view';};
document.querySelector('#expression').onchange=e=>{expression=e.target.value;document.querySelector('#face').click();time=0;paused=expression!=='dook';document.querySelector('#pause').textContent=paused?'Play':'Pause';};
let last=performance.now();function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!paused)time+=dt*speed;draw(time);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.__rigLab={expression(name){expression=name;document.querySelector('#expression').value=name;draw(time);},look(value){lookOverride=value;},ferret:f,goose:g,camera,controls,renderer,scene,pose(t,m='bound'){paused=true;mode=m;time=t;draw(t);},side(){lookOverride=0;camera.position.set(7,2,0);controls.target.set(0,1.0,-.35);controls.update();},front(){referenceView();}};
if(new URLSearchParams(location.search).has('compare'))document.querySelector('#compare').click();

const requestedExpression=new URLSearchParams(location.search).get('expression');if(['neutral','grin','happy','dook'].includes(requestedExpression)){document.querySelector('#expression').value=requestedExpression;document.querySelector('#expression').dispatchEvent(new Event('change'));}
