import './style.css';
import {setupInstallAndShare} from './install.js';
import {World} from './world.js';
import {Sound} from './audio.js';
import {dialogueClip} from './dialogue.js';
import {LEVELS,ENDING,makeCourse,resolveHit} from './data.js';
import {PACE,runSpeed,crossesObstacle,impactFraction} from './pacing.js';
const $=s=>document.querySelector(s);
function getSaved(){
 try{
  const value=JSON.parse(localStorage.getItem('dook-save')||'{}');
  return value!==null&&typeof value==='object'&&!Array.isArray(value)?value:{};
 }catch{return {};}
}
const saved=getSaved();
const state={mode:'title',level:0,name:typeof saved.name==='string'?saved.name.slice(0,18):'',unlocked:Math.max(0,Math.min(3,Number(saved.unlocked)||0)),best:Number(saved.best)||0,coins:0,totalCoins:0,lives:3,lane:0,laneX:0,height:0,velocity:0,slide:0,dook:0,invincible:0,shake:0,distance:0,speed:0,rollTime:0,rollDuration:0,bigJumpUsed:false,playing:false,endless:false,seed:7};
const sound=new Sound();sound.enabled=saved.sound!==false;sound.music=saved.music!==false;
const save=()=>{try{localStorage.setItem('dook-save',JSON.stringify({name:state.name,unlocked:state.unlocked,best:state.best,sound:sound.enabled,music:sound.music}));}catch{}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hero=()=>`Ferret ${state.name||'Friend'}`;
$('#app').innerHTML=`<div class="outer-shell"><header class="site-header"><a href="#" id="brand"><span class="brand-mark">d.</span><span>SMALL PAWS.<br>BIG ADVENTURE.</span></a><div class="header-center"><i></i> A VERY URGENT ADVENTURE</div><div class="header-right"><span class="edition">THE POCKET EDITION</span><button type="button" data-share-game class="icon-button" aria-label="Share game" title="Share game"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 15V3m-4 4 4-4 4 4M5 12v8h14v-8"/></svg></button><button type="button" data-install-game class="icon-button" aria-label="Add to home screen" title="Add to home screen"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="5" y="2" width="14" height="20" rx="2"/><path d="M9 11h6m-3-3v6m-1 5h2"/></svg></button><button id="sound-button" class="icon-button" aria-label="Toggle sound">${sound.enabled?'♪':'♪̸'}</button><button id="help-button" class="icon-button" aria-label="How to play">?</button></div></header><main id="game" aria-label="Dook, Dook, Goose game"><div id="world"></div><div class="vignette"></div><div class="grain"></div><div id="ui"></div><div id="toast" role="status"></div><div id="flash"></div></main><footer class="site-footer"><span>© DOOK DOOK GOOSE <b> / </b> MADE FOR LITTLE SCREENS & BIG FEELINGS</span><span>3 CHAPTERS <b>✳</b> 1 VERY GOOD FRIEND</span></footer></div>`;
let world;try{world=new World($('#world'));}catch(error){$('#ui').innerHTML='<section class="fallback"><h1>A little graphics trouble.</h1><p>This adventure needs WebGL. Try a browser with hardware acceleration enabled.</p></section>';throw error;}
let events=[],last=performance.now(),clock=0,story=null,toastTimer,runStart=0,endlessSegment=1;
function mode(m){if(state.mode!==m)sound.cancelVoice?.();state.mode=m;state.playing=m==='playing';$('#game').dataset.mode=m;sound.tick(m,LEVELS[state.level].id);}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2200);}
function button(text,action,cls='primary'){return `<button class="${cls}" data-action="${action}">${text}</button>`;}
function topbar(label){return `<div class="screen-top"><button class="small-button" data-action="home">← TITLE</button><span>${label}</span><span class="little-star">✳</span></div>`;}
function title(){sound.cancelVoice?.();story=null;$('#toast').classList.remove('visible');mode('title');world.setup('woods','title');$('#ui').innerHTML=`<section class="title-screen"><div class="title-copy"><div class="eyebrow"><span class="tiny-line"></span> A LITTLE FERRET. A BIG MISUNDERSTANDING.</div><h1 class="game-logo"><span>DOOK,</span><span>DOOK,</span><span class="goose-word">GOOSE<span class="bang">!</span></span></h1><div class="title-tagline">Some friends are worth<br>running out of the house for.</div><div class="title-actions">${button('<span class="play-triangle">▶</span> LET’S DOOK THIS <span class="button-arrow">↗</span>','start')}<div class="secondary-actions">${button('CHAPTER SELECT','chapters','text-button')}<span>·</span>${button('HOW TO PLAY','help','text-button')}</div></div><div class="save-line">${state.name?`WELCOME BACK, ${esc(hero().toUpperCase())}`:'A SINGLE-PLAYER POCKET ADVENTURE'} <span>✦</span></div></div><div class="urgent-message"><div class="message-icon">✉</div><div><div class="message-meta">GOOSE MICHAEL <span>now</span></div><p>At the zoo. Behind bars. Hurry.</p><span class="message-unread">1 unread message</span></div></div><div class="character-tag"><span>←</span> ${esc(state.name?hero():'YOUR LOCAL CHAOS NOODLE')}<small>professional overthinker</small></div><div class="game-stamp"><span>100%</span><small>UNNECESSARY<br>URGENCY</small></div><div class="title-bottom"><span><i></i> BIG 1998 ENERGY</span><span>SWIPE. JUMP. DOOK.</span></div></section>`;}
function nameScreen(next=()=>intro(0)){mode('name');$('#ui').innerHTML=`<section class="modal-scrim"><form id="name-form" class="paper-panel name-panel"><div class="eyebrow">FIRST THINGS FERRET</div><div class="paw-emblem">✳</div><h2>Every hero<br>needs a name.</h2><p>A little troublemaker.<br>A very important you.</p><label for="player-name">WHAT SHOULD WE CALL YOU?</label><input id="player-name" name="name" maxlength="18" placeholder="Your name" value="${esc(state.name)}" autocomplete="given-name" required /><div class="name-preview">Introducing: <strong id="name-preview">${esc(hero())}</strong></div><button type="submit" class="primary">THAT’S ME. LET’S GO! <span>→</span></button><button type="button" class="text-button" data-action="home">BACK TO TITLE</button></form></section>`;$('#player-name').focus();$('#player-name').addEventListener('input',e=>{e.target.setCustomValidity('');$('#name-preview').textContent=`Ferret ${e.target.value.trim()||'Friend'}`;});$('#name-form').addEventListener('submit',e=>{e.preventDefault();const name=$('#player-name').value.trim();if(!name){$('#player-name').setCustomValidity('Your ferret needs a name.');$('#player-name').reportValidity();return;}state.name=name;save();sound.effect('click');next();});}
function showStory(lines,onEnd,{chapter=state.level,ending=false}={}){mode(ending?'ending':'story');story={lines,index:0,onEnd,chapter,ending};world.setup(LEVELS[chapter].id,ending?'ending':'story');renderStory();}
function playStoryVoice(){
 if(!story)return;
 sound.dialogue?.(dialogueClip(story.lines,story.index),{nextId:dialogueClip(story.lines,story.index+1)});
}
function renderStory(){
 const [who,line]=story.lines[story.index];
 const person=who==='PIP THE FERRET'?hero().toUpperCase():who;
 const isGoose=who==='GOOSE MICHAEL',isSign=who==='EXHIBIT SIGN';
 const level=LEVELS[story.chapter];
 sound.cancelVoice?.();playStoryVoice();
 $('#ui').innerHTML=`<section class="story-screen">${topbar(story.ending?'THE GREAT REVEAL':`CHAPTER ${level.number} / ${level.name.toUpperCase()}`)}<div class="chapter-title"><div class="eyebrow">${story.ending?'ONE VERY GOOD FRIEND':level.tag}</div><h2>${story.ending?'A cold twist.':level.name}</h2><p>${story.ending?'Some emergencies come in a cone.':level.subtitle}</p></div><div class="dialogue-panel"><div class="speaker-portrait ${isGoose?'goose-portrait':isSign?'sign-portrait':'ferret-portrait'}">${isGoose?'G':isSign?'i':'F'}<span>${isGoose?'✦':'✳'}</span></div><div class="dialogue-content"><div class="speaker">${esc(person)} <span>${isSign?'ZOO AUDIO GUIDE':isGoose?(story.ending?'EXTREMELY UNBOTHERED':'INCOMING MESSAGE'):'PROBABLY FINE'}</span></div><p>${esc(line.replace(/\bPip\b/g,hero()))}</p><div class="dialogue-bottom"><span class="dialogue-dots">${story.lines.map((_,i)=>`<i class="${i===story.index?'active':''}"></i>`).join('')}</span><button class="dialogue-replay" data-action="replay-story" aria-label="Replay this line" title="Replay this line">↺ <span>REPLAY</span></button>${button(story.index===story.lines.length-1?(story.ending?'ONE LAST DOOK →':'LET’S GO →'):'NEXT →','next-story','text-button')}</div></div></div><button class="skip-story" data-action="skip-story">SKIP ${story.ending?'TO GELATO':'DIALOGUE'} ↗</button></section>`;
}
function nextStory(){sound.effect('click');if(++story.index>=story.lines.length){const end=story.onEnd;story=null;end();}else renderStory();}
function intro(i){state.level=i;state.endless=false;showStory(LEVELS[i].dialogues,()=>briefing(i),{chapter:i});}
function briefing(i){mode('briefing');const l=LEVELS[i];$('#ui').innerHTML=`<section class="modal-scrim"><div class="paper-panel briefing-panel"><span class="chapter-pill">CHAPTER ${l.number}</span><h2>${l.name}</h2><p>${l.subtitle}</p><div class="mechanic-card"><span>YOUR SPECIAL MOVE</span><h3>${l.mechanic}</h3><p>${l.tip}</p></div><div class="compact-controls"><span>↔<small>SWITCH LANES</small></span><span>↑<small>JUMP ×2</small></span><span>↓<small>SLIDE</small></span></div>${button('READY, FERRET, GO! →','run')}<small class="keyboard-hint">Keyboard: ← → to move · ↑ / Space to jump · ↓ to slide · D to dook · R for a BIG barrel roll</small></div></section>`;}
function startRun({retry=false}={}){
 mode('playing');const l=LEVELS[state.level];Object.assign(state,{lane:0,laneX:0,height:0,velocity:0,slide:0,dook:0,invincible:0,shake:0,distance:0,speed:l.speed,lives:3,coins:0,rollTime:0,rollDuration:0,bigJumpUsed:false});if(!retry&&state.level===0)state.totalCoins=0;world.setup(l.id,'run');events=[];endlessSegment=1;addCourse(0);runStart=clock;renderHUD();toast(state.endless?'NO FINISH LINE. JUST DOOK.':l.tip);sound.effect('ready');
}
function addCourse(offset){for(const e of makeCourse(LEVELS[state.level],state.endless,state.seed,offset))events.push({...e,mesh:null,hit:false});}
function renderHUD(){const l=LEVELS[state.level];$('#ui').innerHTML=`<section class="play-screen"><div class="hud-top"><div class="hud-chapter"><span>${state.endless?'ENDLESS ADVENTURE':`CHAPTER ${l.number}`}</span><strong>${l.name}</strong></div><button class="pause-button" data-action="pause" aria-label="Pause game">Ⅱ</button></div><div class="hud-stats"><div class="hearts" aria-label="Lives" id="lives">♥ ♥ ♥</div><div class="coin-count"><span>✦</span> <b id="coin-count">000</b></div></div><div class="progress-track"><div id="progress"></div><span>⚑</span></div><div id="distance-label">0 m</div><div id="action-cue"></div><div class="run-bottom"><span class="runner-name">${esc(hero().toUpperCase())}</span><div class="touch-controls"><button data-control="left" aria-label="Move left">←</button><button data-control="slide" aria-label="Slide">↓<small>SLIDE</small></button><button data-control="jump" aria-label="Jump">↑<small>JUMP ×2</small></button><button data-control="right" aria-label="Move right">→</button><button class="dook-button" data-control="dook">DOOK!<small>D</small></button></div></div></section>`;}
function bigJump(force=false){if(state.bigJumpUsed&&!force)return;state.bigJumpUsed=true;state.slide=0;state.height=Math.max(.06,state.height);state.velocity=PACE.bigJumpVelocity;state.rollTime=0;state.rollDuration=(state.velocity+Math.sqrt(state.velocity*state.velocity+2*PACE.gravity*state.height))/PACE.gravity;sound.effect(force?'bounce':'roll');toast('BARREL DOOK! 360° OF FERRET ENERGY.');}
function action(a){if(state.mode!=='playing')return;sound.start();if(a==='left')state.lane=Math.max(-1,state.lane-1);if(a==='right')state.lane=Math.min(1,state.lane+1);if(a==='roll'||(a==='jump'&&state.height>.15)){bigJump();return;}if(a==='jump'&&state.height<=.05){state.velocity=PACE.jumpVelocity;state.height=.06;state.slide=0;sound.effect('jump');}if(a==='slide'){const entering=state.slide<=0||state.height>.05;state.slide=PACE.slideDuration;if(state.height>.05)state.velocity=Math.min(state.velocity,-PACE.diveVelocity);if(entering)sound.effect('slide');}if(a==='dook'){if(state.dook>0)return;state.dook=PACE.dookDuration;sound.effect('dook');toast('DOOK DOOK!');for(const e of events)if(e.type==='gate'&&!e.hit&&e.distance-state.distance<state.speed*PACE.dookLeadTime&&e.distance-state.distance>0){e.hit=true;if(e.mesh)e.mesh.rotation.z=1.3;sound.effect('gate');toast('EXCUSE ME, IMPORTANT FERRET COMING THROUGH!');}}}
function hit(){if(state.invincible>0)return;state.lives--;state.invincible=1.8;state.shake=.3;sound.effect('hit');$('#flash').classList.add('hit');setTimeout(()=>$('#flash').classList.remove('hit'),220);if(navigator.vibrate)navigator.vibrate(60);if(state.lives<=0)fail();else toast(['A tactical bonk. Keep going!','Still extremely aerodynamic.'][state.lives%2]);}
function tick(dt){
 const previousDistance=state.distance,previousHeight=state.height,previousX=state.laneX;
 state.distance+=state.speed*dt;state.speed=runSpeed(LEVELS[state.level],state.distance,state.endless);state.laneX+=(state.lane*2.3-state.laneX)*(1-Math.exp(-PACE.laneResponse*dt));state.invincible=Math.max(0,state.invincible-dt);state.shake=Math.max(0,state.shake-dt);state.slide=Math.max(0,state.slide-dt);state.dook=Math.max(0,state.dook-dt);
 if(state.height>0||state.velocity>0){state.height=Math.max(0,state.height+state.velocity*dt-.5*PACE.gravity*dt*dt);state.velocity-=PACE.gravity*dt;if(state.rollDuration)state.rollTime=Math.min(state.rollDuration,state.rollTime+dt);if(state.height===0){if(previousHeight>0)sound.effect('land');state.velocity=0;state.bigJumpUsed=false;state.rollTime=0;state.rollDuration=0;}}
 if(state.endless&&state.distance>endlessSegment*PACE.endlessSegmentLength-state.speed*3){addCourse(endlessSegment*PACE.endlessSegmentLength);endlessSegment++;}
 let cue='';for(const e of events){const ahead=e.distance-state.distance;if(!e.mesh&&ahead<105&&ahead>-5&&!e.hit)e.mesh=world.obstacle(e.type,e.lane,ahead);if(e.mesh){e.mesh.position.z=4-ahead;if(e.type==='coin'||e.type==='heart'){e.mesh.rotation.y=clock*2;e.mesh.position.y=Math.sin(clock*3+e.distance)*.08;}if(ahead<-10){world.removeObject(e.mesh);e.mesh=null;}}
  if(!e.hit&&ahead>0){
   const arrival=ahead/state.speed;
   if(e.type==='gate'&&arrival<PACE.dookLeadTime)cue='DOOK! OPEN THE GATE';
   if(e.type==='window'&&arrival<1.5)cue=arrival<.40?'JUMP → FREEDOM!':'WINDOW AHEAD · CENTER LANE';
   if(e.type==='spring'&&e.lane===state.lane&&arrival<1.1)cue=arrival<.40?'JUMP ON THE MUSHROOM!':'MUSHROOM AHEAD · GET READY TO JUMP';
   if(e.type==='low'&&e.lane===state.lane&&arrival<1.1)cue=arrival<.40?'↓ SLIDE UNDER':'LOW OBSTACLE AHEAD · GET READY TO SLIDE';
  }
  if(e.hit||!crossesObstacle(e.distance,previousDistance,state.distance))continue;
  const impact=impactFraction(e.distance,previousDistance,state.distance);
  const collisionX=previousX+(state.laneX-previousX)*impact;
  const collisionHeight=previousHeight+(state.height-previousHeight)*impact;
  const sameLane=Math.abs(collisionX-e.lane*2.3)<.95;
  if(e.type==='window'&&!sameLane){e.hit=true;hit();if(state.mode==='playing'){state.distance=LEVELS[state.level].length-state.speed*1.2;e.hit=false;state.lane=0;state.laneX=0;toast('THE WINDOW IS IN THE CENTER. JUMP!');}continue;}
  if(!sameLane&&e.type!=='finish')continue;
  if((e.type==='coin'||e.type==='heart')&&collisionHeight>2)continue;
  e.hit=true;const result=resolveHit(e.type,{height:collisionHeight,slide:state.slide>0,dook:state.dook>0});
  if(e.type==='coin'){state.coins++;sound.effect('coin');e.mesh?.scale.setScalar(0);}else if(e.type==='heart'){state.lives=Math.min(3,state.lives+1);sound.effect('heart');e.mesh?.scale.setScalar(0);toast('A LITTLE SECOND WIND. +1 HEART');}else if(result==='bounce'){state.height=Math.max(state.height,.8);bigJump(true);toast('MUSHROOM AIRLINES. NO REFUNDS.');}else if(result==='damage'){hit();if(e.type==='window'&&state.mode==='playing'){state.distance=LEVELS[state.level].length-state.speed*1.2;e.hit=false;toast('ONE MORE TRY. JUMP THROUGH THE WINDOW!');}}
  else if(result==='escape'){sound.effect('window');toast('A PERFECTLY NORMAL WAY TO LEAVE A HOUSE.');}
  if(state.mode!=='playing')return;
 }
 events=events.filter(e=>e.distance>state.distance-20);
 if(!state.endless&&state.distance>LEVELS[state.level].length+3){complete();return;}
 $('#lives').innerHTML=Array.from({length:3},(_,i)=>`<span class="${i>=state.lives?'lost':''}">♥</span>`).join(' ');$('#coin-count').textContent=String(state.coins).padStart(3,'0');$('#progress').style.width=`${state.endless?(state.distance%PACE.endlessSegmentLength)/PACE.endlessSegmentLength*100:state.distance/LEVELS[state.level].length*100}%`;$('#distance-label').textContent=`${Math.floor(state.distance)} m${state.endless?' · ∞':''}`;$('#action-cue').textContent=cue;$('#action-cue').classList.toggle('show',!!cue);
}
function pause(){if(state.mode!=='playing')return;mode('paused');$('#ui').insertAdjacentHTML('beforeend',`<section class="modal-scrim" id="pause-overlay"><div class="paper-panel"><div class="eyebrow">TAKE A LITTLE BREATHER</div><h2>Paused.<br>Still urgent.</h2><p>Goose can wait.<br>Probably.</p>${button('KEEP DOOKING →','resume')}${button('HOW TO PLAY','help','outline-button')}${button('BACK TO TITLE','home','text-button')}</div></section>`);}
function resume(){mode('playing');$('#pause-overlay')?.remove();}
function complete(){mode('result');state.totalCoins+=state.coins;state.unlocked=Math.max(state.unlocked,state.level+1);state.best=Math.max(state.best,state.totalCoins);save();sound.effect('win');const l=LEVELS[state.level];$('#ui').innerHTML=`<section class="modal-scrim"><div class="paper-panel result-panel"><div class="eyebrow">CHAPTER ${l.number} COMPLETE</div><div class="result-seal">✦</div><h2>${state.level===0?'Out the window.':state.level===1?'Naturally gifted.':'Goose located.'}</h2><p>${state.level===0?'One small leap for ferret.<br>One large problem for the curtains.':state.level===1?'You came. You saw.<br>You got a leaf stuck to your butt.':'Rescue mission status:<br>Unexpectedly delicious.'}</p><div class="result-stats"><div><b>${state.coins}</b><span>SHINY THINGS</span></div><div><b>${Math.round(clock-runStart)}s</b><span>URGENTLY SPENT</span></div><div><b>${'♥'.repeat(state.lives)}</b><span>FERRET ENERGY</span></div></div>${button(state.level===2?'FIND OUT WHAT HAPPENED →':'ONWARD, LITTLE NOODLE →','continue')}${button('BACK TO TITLE','home','text-button')}</div></section>`;}
function fail(){mode('failed');sound.effect('fail');state.best=Math.max(state.best,state.coins+state.totalCoins);save();$('#ui').innerHTML=`<section class="modal-scrim"><div class="paper-panel"><div class="eyebrow">A MINOR FERRET-RELATED SETBACK</div><h2>Oh, dook.</h2><p>${esc(hero())} needs a breather.<br>The rescue is still very much on.</p><div class="result-stats"><div><b>${Math.floor(state.distance)}m</b><span>DISTANCE</span></div><div><b>${state.coins}</b><span>SHINY THINGS</span></div></div>${button('ONE MORE DOOK →','retry')}${button('BACK TO TITLE','home','text-button')}</div></section>`;}
function credits(){mode('credits');state.unlocked=3;save();$('#ui').innerHTML=`<section class="ending-screen"><div class="eyebrow">THE END. THE GELATO IS ONLY THE BEGINNING.</div><h2>A very good<br>misunderstanding.</h2><div class="ending-note">${esc(hero())} saved absolutely no one.<br>And had a very nice afternoon.</div><div class="credits-card"><div class="eyebrow">STARRING</div><p>${esc(hero())}<small>AS THE LOCAL CHAOS NOODLE</small></p><p>Goose Michael<small>AS A FRIEND WITH POOR TEXTING SKILLS</small></p><div class="credits-score">✦ ${state.totalCoins} SHINY THINGS · FRIENDSHIP: IMMEASURABLE</div>${button('THE ADVENTURE NEVER ENDS ↗','endless')}<div class="secondary-actions">${button('PLAY AGAIN','start','text-button')}${button('TITLE SCREEN','home','text-button')}</div></div><div class="end-credit">NO GEESE WERE RESCUED IN THE MAKING OF THIS GAME.</div></section>`;}
function chapters(){mode('chapters');$('#ui').innerHTML=`<section class="chapter-select">${topbar('CHOOSE YOUR CHAOS')}<div class="select-heading"><div class="eyebrow">THREE CHAPTERS. ZERO CRITICAL THINKING.</div><h2>The scenic route.</h2><p>A small adventure, with a very big heart.</p></div><div class="chapter-cards">${LEVELS.map((l,i)=>`<button class="chapter-card ${l.id}" data-chapter="${i}" ${state.unlocked<i?'disabled':''}><div class="chapter-art"><span class="chapter-number">${l.number}</span><div class="chapter-art-icon">${['⌂','♠','⚑'][i]}</div><span class="chapter-status">${state.unlocked<i?'LOCKED':state.unlocked>i?'✓ COMPLETE':'READY TO RUN'}</span></div><div class="chapter-card-copy"><span>${l.tag}</span><h3>${l.name}</h3><p>${l.subtitle}</p><div>${state.unlocked<i?'COMPLETE THE PREVIOUS CHAPTER':'LET’S GO'} <b>↗</b></div></div></button>`).join('')}</div><div class="chapter-select-footer">${state.unlocked===3?button('ENDLESS MODE ∞','endless','outline-button'):'PLAY THE STORY TO UNLOCK EVERY CHAPTER.'}${button('CHANGE FERRET NAME','rename','text-button')}</div></section>`;}
function help(){const wasPlaying=state.mode==='playing';if(wasPlaying)pause();const prev=$('#help-overlay');if(prev)return;$('#ui').insertAdjacentHTML('beforeend',`<section class="modal-scrim" id="help-overlay"><div class="paper-panel help-panel"><div class="eyebrow">THE ART OF DOOKING</div><h2>Little legs.<br>Big moves.</h2><div class="help-rows"><div><b>↔</b><p><strong>SWITCH LANES</strong>Swipe left or right. Dodge the chunky stuff.<small>KEYBOARD: ← → · A ALSO MOVES LEFT</small></p></div><div><b>↑</b><p><strong>GET AIRBORNE</strong>Swipe up to jump. Jump again in the air for a BIG barrel roll!<small>↑ / SPACE TO JUMP · TWICE TO ROLL · R = BIG JUMP</small></p></div><div><b>↓</b><p><strong>BECOME NOODLE</strong>Swipe down to dive into a slide. Zip under tables and branches.<small>KEYBOARD: ↓ OR S</small></p></div><div><b>!</b><p><strong>DOOK WITH PURPOSE</strong>Tap DOOK! to open zoo gates.<small>KEYBOARD: D OR E</small></p></div></div><p class="help-note">Collect ✦ shiny things. Pink hearts restore energy. Three bonks = a breather. Touch buttons work too.</p><div class="settings-row"><label><input id="music-toggle" type="checkbox" ${sound.music?'checked':''}> ADVENTURE MUSIC</label><span>BEST: ${state.best} ✦</span></div><div class="dook-title-tools"><button type="button" class="dook-tool-button" data-share-game>SHARE ↗</button><button type="button" class="dook-tool-button" data-install-game>ADD TO HOME SCREEN +</button></div>${button('GOT IT. LET’S DOOK.','close-help')}</div></section>`);$('#music-toggle').addEventListener('change',e=>{sound.music=e.target.checked;save();});}
$('#ui').addEventListener('click',e=>{
 const control=e.target.closest('[data-control]');if(control){action(control.dataset.control);return;}const chapter=e.target.closest('[data-chapter]');if(chapter){state.endless=false;const go=()=>intro(Number(chapter.dataset.chapter));state.name?go():nameScreen(go);return;}
 const b=e.target.closest('[data-action]');if(!b)return;sound.start();const a=b.dataset.action;if(!['resume','next-story'].includes(a))sound.effect('click');
 const actions={home:title,start:()=>{state.totalCoins=0;nameScreen();},rename:()=>nameScreen(title),chapters,help,'close-help':()=>$('#help-overlay')?.remove(),'next-story':nextStory,'replay-story':playStoryVoice,'skip-story':()=>{sound.cancelVoice?.();const end=story.onEnd;story=null;end();},run:()=>startRun(),pause,resume,retry:()=>startRun({retry:true}),continue:()=>{if(state.level===2)showStory(ENDING,credits,{chapter:2,ending:true});else{const prev=state.level;showStory(LEVELS[prev].exit,()=>intro(prev+1),{chapter:prev});}},endless:()=>{state.endless=true;state.level=1;state.totalCoins=0;const go=()=>startRun();state.name?go():nameScreen(go);}};actions[a]?.();
});
$('#brand').addEventListener('click',e=>{e.preventDefault();if(state.mode==='playing')pause();else title();});$('#sound-button').addEventListener('click',()=>{sound.start();sound.enabled=!sound.enabled;$('#sound-button').textContent=sound.enabled?'♪':'♪̸';$('#sound-button').setAttribute('aria-label',sound.enabled?'Mute sound':'Enable sound');save();});$('#help-button').addEventListener('click',help);
window.addEventListener('keydown',e=>{if(e.target instanceof Element&&e.target.matches('input'))return;const keys={ArrowLeft:'left',a:'left',ArrowRight:'right',ArrowUp:'jump',' ':'jump',w:'jump',ArrowDown:'slide',s:'slide',d:'dook',e:'dook',r:'roll'};if(keys[e.key]){if(e.repeat&&['jump','roll'].includes(keys[e.key]))return;if(state.mode==='playing')e.preventDefault();action(keys[e.key]);}if(e.key==='Escape'||e.key==='p'){if($('#help-overlay'))$('#help-overlay').remove();else if(state.mode==='playing')pause();else if(state.mode==='paused')resume();}if(e.key==='Enter'&&story)nextStory();});
let touch=null;$('#game').addEventListener('pointerdown',e=>{if(state.mode!=='playing'||e.target.closest('button'))return;touch={x:e.clientX,y:e.clientY};});$('#game').addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;action(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'slide':'jump'));});$('#game').addEventListener('pointercancel',()=>touch=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();});window.addEventListener('blur',()=>{if(state.mode==='playing')pause();});
setupInstallAndShare({onOpen:()=>{if(state.mode==='playing')pause();}});
let lastPawPhase=0;
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;clock+=dt;if(state.playing)tick(dt);world.update(clock,dt,state);const pawPhase=world.player.stats.phase||0;if(state.playing&&state.height===0&&state.slide===0&&pawPhase<lastPawPhase)sound.effect('paws');lastPawPhase=pawPhase;sound.tick(state.mode,LEVELS[state.level].id);requestAnimationFrame(frame);}title();requestAnimationFrame(frame);
// Read-only runtime snapshot for smoke tests and graphics inspection.
window.__dook={audio:()=>sound.snapshot?.(),snapshot:()=>({mode:state.mode,level:state.level,name:state.name,lives:state.lives,distance:state.distance,coins:state.coins,lane:state.lane,laneX:state.laneX,speed:state.speed,height:state.height,slide:state.slide,endless:state.endless,unlocked:state.unlocked,objects:world.renderer.info.render.calls,rigBones:world.player.rig.bones.length,motion:world.player.stats.motion,expression:world.player.stats.expression,facialBones:world.player.faceRig.bones.length,arch:world.player.stats.arch,hop:world.player.stats.hop||0,gaitRate:world.player.stats.gaitRate||0,roll:world.player.stats.roll,rollProgress:state.rollDuration?state.rollTime/state.rollDuration:0}),getCourse:()=>events.filter(e=>!e.hit).map(({type,lane,distance})=>({type,lane,distance})).slice(0,20)};
